dependencies:
  - name: cassandra
    version: 5.1.3
    condition: cassandra.enabled
    repository: https://charts.bitnami.com/bitnami
  - name: memcached
    version: 2.6.0
    condition: memcached.enabled
  - name: memcached-index-read
    version: 2.6.0
    condition: memcached-index-read.enabled
  - name: memcached-index-write
    version: 2.6.0
    condition: memcached-index-write.enabled
